apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-api
  labels:
    app: student-api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: student-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: app-credentials
  data:
    - secretKey: DB_USER
      remoteRef:
        key: student-api
        property: DB_USER
    - secretKey: DB_PASS
      remoteRef:
        key: student-api
        property: DB_PASS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: student-api
          image: kiril011/student-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres.student-api.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: studentdb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
